//2013 © Rotesource, Inc. http://rotesource.com/bigcommerce-agegate (Goke Pelemo - http://goke.me)
function readCookie(name) {
	var nameEQ = name + "=";
	var ca = document.cookie.split(';');
	for(var i=0;i < ca.length;i++) {
		var c = ca[i];
		while (c.charAt(0)==' ') c = c.substring(1,c.length);
		if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
	}
	return null;
};

var goke = readCookie('Bouncer');
if (goke) {
     document.write("<style> #AgeGate { visibility:hidden; }</style>");
};

//2013 © Rotesource, Inc. http://rotesource.com/bigcommerce-agegate (Goke Pelemo - http://goke.me)
if (goke == null || goke=='') {
	document.write("<link rel=\"stylesheet\" href=\"http://yui.yahooapis.com/pure/0.3.0/pure-min.css\"\/>");
	document.write("<div id=\"AgeGate\" class=\"pure-form\" style=\"position:absolute; top: 5px; left: 0px; z-index: 3000; ");
    document.write("                height: 5000px; width: 100%; background-color:rgba(255, 255, 255, 0.98);text-align:center;\">");
//The Logo Image TIP: Its way cooler to use one with a transparent background.
	document.write("    <img src=\"http://img.rotesource.com/700x300.png\"\/> <br\/><br\/>");
//The Logo Image - END
    document.write("    <h3 style=\"text-align:center;width:500px;margin:0 auto;\">WARNING!!! THIS SITE IS 18+: THIS SITE CONTAINS MATERIAL OF AN ADULT NATURE AND BY PROCEEDING YOU HAVE ACKNOWLEDGED YOUR DESIRE TO VIEW SUCH CONTENT AND VERIFY THAT YOU ARE OF LEGAL AGE TO DO SO.<\/h3>");
//The Disclaimer
	document.write("    <p style=\"text-align: center;\">SELECT YOUR DATE OF BIRTH BELOW<\/p>");
//The Disclaimer - END
	document.write("	<h2><select name=\"bmonth\" id=\"bmonth\">");
    document.write("  			<option value=\"0\">January<\/option>");
    document.write("  			<option value=\"1\">February<\/option>");
    document.write("  			<option value=\"2\">March<\/option>");
    document.write("  			<option value=\"3\">April<\/option>");
    document.write("  			<option value=\"4\">May<\/option>");
    document.write("  			<option value=\"5\">June<\/option>");
    document.write("  			<option value=\"6\">July<\/option>");
    document.write("  			<option value=\"7\">August<\/option>");
    document.write("  			<option value=\"8\">September<\/option>");
    document.write("  			<option value=\"9\">October<\/option>");
    document.write("  			<option value=\"10\">November<\/option>");
    document.write("  			<option value=\"11\">December<\/option>");
    document.write("		<\/select>");
    document.write("");
    document.write("    	<select name=\"bday\" id=\"bday\">");
    document.write("  			<option value=\"1\">1<\/option>");
    document.write("  			<option value=\"2\">2<\/option>");
    document.write("  			<option value=\"3\">3<\/option>");
    document.write(" 		 	<option value=\"4\">4<\/option>");
    document.write("  			<option value=\"5\">5<\/option>");
    document.write("  			<option value=\"6\">6<\/option>");
    document.write("  			<option value=\"7\">7<\/option>");
    document.write("  			<option value=\"8\">8<\/option>");
    document.write("  			<option value=\"9\">9<\/option>");
    document.write("  			<option value=\"10\">10<\/option>");
    document.write("  			<option value=\"11\">11<\/option>");
    document.write("  			<option value=\"12\">12<\/option>");
    document.write("  			<option value=\"13\">13<\/option>");
    document.write("  			<option value=\"14\">14<\/option>");
    document.write("  			<option value=\"15\">15<\/option>");
    document.write("  			<option value=\"16\">16<\/option>");
    document.write("  			<option value=\"17\">17<\/option>");
    document.write("  			<option value=\"18\">18<\/option>");
    document.write("  			<option value=\"19\">19<\/option>");
    document.write("  			<option value=\"20\">20<\/option>");
    document.write("  			<option value=\"21\">21<\/option>");
    document.write("  			<option value=\"22\">22<\/option>");
    document.write("  			<option value=\"23\">23<\/option>");
    document.write("  			<option value=\"24\">24<\/option>");
    document.write("  			<option value=\"25\">25<\/option>");
    document.write("  			<option value=\"26\">26<\/option>");
    document.write("  			<option value=\"27\">27<\/option>");
    document.write("  			<option value=\"28\">28<\/option>");
    document.write("  			<option value=\"29\">29<\/option>");
    document.write("  			<option value=\"30\">30<\/option>");
    document.write("  			<option value=\"31\">31<\/option>");
    document.write("		<\/select>");
    document.write("");
    document.write("    	<select name=\"byear\" id=\"byear\">");
    document.write("  			<option value=\"2012\">2012<\/option>");
    document.write("  			<option value=\"2011\">2011<\/option>");
    document.write("  			<option value=\"2010\">2010<\/option>");
    document.write("  			<option value=\"2009\">2009<\/option>");
    document.write("  			<option value=\"2008\">2008<\/option>");
    document.write("  			<option value=\"2007\">2007<\/option>");
    document.write("  			<option value=\"2006\">2006<\/option>");
    document.write("  			<option value=\"2005\">2005<\/option>");
    document.write("  			<option value=\"2004\">2004<\/option>");
    document.write("  			<option value=\"2003\">2003<\/option>");
    document.write("  			<option value=\"2002\">2002<\/option>");
    document.write("  			<option value=\"2001\">2001<\/option>");
    document.write("  			<option value=\"2000\">2000<\/option>");
    document.write("  			<option value=\"1999\">1999<\/option>");
    document.write("  			<option value=\"1998\">1998<\/option>");
    document.write("  			<option value=\"1997\">1997<\/option>");
    document.write("  			<option value=\"1996\">1996<\/option>");
    document.write("  			<option value=\"1995\">1995<\/option>");
    document.write("  			<option value=\"1994\">1994<\/option>");
    document.write("  			<option value=\"1993\">1993<\/option>");
    document.write("  			<option value=\"1992\">1992<\/option>");
    document.write("  			<option value=\"1991\">1991<\/option>");
    document.write("  			<option value=\"1990\">1990<\/option>");
    document.write("  			<option value=\"1989\">1989<\/option>");
    document.write("  			<option value=\"1988\">1988<\/option>");
    document.write(" 			<option value=\"1987\">1987<\/option>");
    document.write("  			<option value=\"1986\">1986<\/option>");
    document.write("  			<option value=\"1985\">1985<\/option>");
    document.write("  			<option value=\"1984\">1984<\/option>");
    document.write("  			<option value=\"1983\">1983<\/option>");
    document.write("  			<option value=\"1982\">1982<\/option>");
    document.write("  			<option value=\"1981\">1981<\/option>");
    document.write("  			<option value=\"1980\">1980<\/option>");
    document.write("  			<option value=\"1979\">1979<\/option>");
    document.write("  			<option value=\"1978\">1978<\/option>");
    document.write("  			<option value=\"1977\">1977<\/option>");
    document.write("  			<option value=\"1976\">1976<\/option>");
    document.write("  			<option value=\"1975\">1975<\/option>");
    document.write("  			<option value=\"1974\">1974<\/option>");
    document.write("  			<option value=\"1973\">1973<\/option>");
    document.write("  			<option value=\"1972\">1972<\/option>");
    document.write("  			<option value=\"1971\">1971<\/option>");
    document.write("  			<option value=\"1970\">1970<\/option>");
    document.write("  			<option value=\"1969\">1969<\/option>");
    document.write("  			<option value=\"1968\">1968<\/option>");
    document.write("  			<option value=\"1967\">1967<\/option>");
    document.write("  			<option value=\"1966\">1966<\/option>");
    document.write("  			<option value=\"1965\">1965<\/option>");
    document.write("  			<option value=\"1964\">1964<\/option>");
    document.write("  			<option value=\"1963\">1963<\/option>");
    document.write("  			<option value=\"1962\">1962<\/option>");
    document.write("  			<option value=\"1961\">1961<\/option>");
    document.write("  			<option value=\"1960\">1960<\/option>");
    document.write("  			<option value=\"1959\">1959<\/option>");
    document.write("  			<option value=\"1958\">1958<\/option>");
    document.write("  			<option value=\"1957\">1957<\/option>");
    document.write("  			<option value=\"1956\">1956<\/option>");
    document.write("  			<option value=\"1955\">1955<\/option>");
    document.write("  			<option value=\"1954\">1954<\/option>");
    document.write("  			<option value=\"1953\">1953<\/option>");
    document.write("  			<option value=\"1952\">1952<\/option>");
    document.write("  			<option value=\"1951\">1951<\/option>");
    document.write("  			<option value=\"1950\">1950<\/option>");
    document.write("  			<option value=\"1949\">1949<\/option>");
    document.write("  			<option value=\"1948\">1948<\/option>");
    document.write("  			<option value=\"1947\">1947<\/option>");
    document.write("  			<option value=\"1946\">1946<\/option>");
    document.write("  			<option value=\"1945\">1945<\/option>");
    document.write("  			<option value=\"1944\">1944<\/option>");
    document.write("  			<option value=\"1943\">1943<\/option>");
    document.write("  			<option value=\"1942\">1942<\/option>");
    document.write("  			<option value=\"1941\">1941<\/option>");
    document.write("  			<option value=\"1940\">1940<\/option>");
    document.write("  			<option value=\"1939\">1939<\/option>");
    document.write("  			<option value=\"1938\">1938<\/option>");
    document.write("  			<option value=\"1937\">1937<\/option>");
    document.write("  			<option value=\"1936\">1936<\/option>");
    document.write("  			<option value=\"1935\">1935<\/option>");
    document.write("  			<option value=\"1934\">1934<\/option>");
    document.write("  			<option value=\"1933\">1933<\/option>");
    document.write("  			<option value=\"1932\">1932<\/option>");
    document.write("  			<option value=\"1931\">1931<\/option>");
    document.write("  			<option value=\"1930\">1930<\/option>");
    document.write("  			<option value=\"1929\">1929<\/option>");
    document.write("  			<option value=\"1928\">1928<\/option>");
    document.write("  			<option value=\"1927\">1927<\/option>");
    document.write("  			<option value=\"1926\">1926<\/option>");
    document.write("  			<option value=\"1925\">1925<\/option>");
    document.write("  			<option value=\"1924\">1924<\/option>");
    document.write("  			<option value=\"1923\">1923<\/option>");
    document.write("  			<option value=\"1922\">1922<\/option>");
    document.write("  			<option value=\"1921\">1921<\/option>");
    document.write("  			<option value=\"1920\">1920<\/option>");
    document.write("  			<option value=\"1919\">1919<\/option>");
    document.write("  			<option value=\"1918\">1918<\/option>");
    document.write("  			<option value=\"1917\">1917<\/option>");
    document.write("  			<option value=\"1916\">1916<\/option>");
    document.write("  			<option value=\"1915\">1915<\/option>");
    document.write("  			<option value=\"1914\">1914<\/option>");
    document.write("  			<option value=\"1913\">1913<\/option>");
    document.write("   		<\/select>&nbsp;&nbsp;<button type=\"submit\" class=\"pure-button\" style=\"color: white;border-radius: 4px;text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);background: rgb(66, 184, 221);\" id=\"submit_birthdate\" ");
    document.write("           onclick=\"ageCheck()\" \/>Enter<\/button>");
    document.write("	<\/h2>");
    document.write("    <h4 id=\"AgeGate\" style=\"font-size:0.8em;\">You must have Javascript and Cookies enabled to use this website.<\/h4>");
    document.write("<\/div>");
//The message displayed when the visitor has Javascript disabled
	document.write("  			<noscript>");
    document.write("  			<div style=\"position: absolute; top: 10px; left: 0px; z-index: 3000; height: 100%; width: 100%; background-color: #FFFFFF;text-align:center;\">");
    document.write("  			<h1>JavaScript is not enabled.<\/h1><br \/>");
    document.write("  			<h2 style=\"margin: 10px;\">This site contains age restricted material; your browser must have JavaScript and Cookies enabled to access it.<\/h2><br \/>");
    document.write("  			<h2>Thank You<\/h2>");
    document.write("  			<\/div>");
    document.write("  			<\/noscript>");
//The message displayed when the visitor has Javascript disabled - END
}
